<?php

//var_dump($this->form_data); exit;

?>

<form id="media" method="post" action="/<?php echo $this->element->getAction() ?>" enctype="application/x-www-form-urlencoded">

<table  class="add" align=center width=800 border=0 cellspacing=3>
<caption>
</caption>
<tr>
	<td><label class="required" for="login">Preference ID</label></td>
	<td><?php echo $this->element->id->getValue(); ?></td>
</tr>
<tr>
	<td><label class="required" for="title">Title</label></td>
	<td><?php echo $this->element->title ?></td>
</tr>
<tr>
	<td><label class="required" for="media_url">Description</label></td>
	<td><?php echo $this->element->description ?>
	</td>
</tr>

<tr>
	<td><label class="required" for="last_updated">Last Updated</label></td>
	<td><?php echo $this->element->last_updated->getValue(); ?>
	</td>
</tr>

<tr>
	<td><label class="required" for="creation_date">Creation Date</label></td>
	<td><?php echo $this->element->creation_date->getValue(); ?>
	</td>
</tr>


<tr>
	<td></td>
	<td>
		<?php echo $this->element->submit ?>
	</td>
</tr>



</table>



</form>

<br>
<br>
