<?php

//var_dump($this->dataArray); exit;
//var_dump($this->tableMetaData); exit;
//var_dump($this->tableColumnNames); exit;
$cbArray = '';
$table_form_name = 'AdmAclPreference';

?>

<div>
	<table width=100% border=0>
		<caption></caption>
		<tr>
			<td><?php  echo $this->searchbox; ?>
			</td>
			<?php  if (!empty($this->q)) {?>
				<td><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/list/">[X]</a>
				</td>
			<?php } ?>
			<td width=70%>This is the list of acl_preference in the system. Administer these records.
			</td>
		</tr>
	</table>
</div>

<?php if (!empty($this->dataArray)){ ?>
<form name="<? echo $table_form_name ?>" action="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/<?php echo $this->myAction; ?>" method="post">
<table class="table_list">
<tr>
	<th>Del</th>
	<?php foreach ($this->tableColumnNames as $column_name) { ?>
		<th><?php echo ucfirst($column_name) ?></th>
	<?php } ?>
</tr>

	
<?php
foreach($this->dataArray as $record) {
	$cbArray .= $record['id'] .",";
?>
	<tr onMouseover="this.style.backgroundColor='#e0e0e0'" onMouseout="this.style.backgroundColor='#FFFFFF'">
		<td>
			<input type=checkbox name="actioncb_<?php echo $record['id'] ?>">
		</td>
		<td>
			<?php if (!empty($record['id'])){ ?>
			<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/edit/id/<?php echo $record['id'] ?>">
				<?php echo $record['id'] ?>
			</a>
			<?php } ?>
		</td>
		<td>
			<?php if (!empty($record['id'])){ ?>
			<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/edit/id/<?php echo $record['id'] ?>">
				<?php echo $record['title'] ?>
			</a>
			<?php } ?>
		</td>
		<td><?php echo $record['description'] ?></td>
		<td><?php echo $this->getStatus($record['status']) ?></td>
		<td><?php echo $record['creation_date'] ?></td>
		<td><?php echo $record['last_updated'] ?></td>
	</tr>

<?php } ?>

</table>
<br>
<?php echo $this->Paginator($this->baseURL . '/' . $this->myController . '/' . $this->myAction, $this->page, $this->last_page, 'AdmAclUser'); ?>

<?php }else{ ?>
	No records found.
<?php } ?>

<br>
<br>

<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/add" />[Add]</a>
<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/emptytable" />[Empty Table]</a>
<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/droptable" />[Drop Table]</a>
<a href="<?php print $this->baseURL; ?>/Admin/" />[Admin Menu]</a>

<br><br>
View Filter<br>
<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/list/f/<?php echo ADMIN_DAO_ACL_Role::FILTER_NONE ?>" />(None)</a><br></br>
<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/list/f/<?php echo ADMIN_DAO_ACL_Role::FILTER_ACTIVE ?>" />(Active)</a><br></br>
<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/list/f/<?php echo ADMIN_DAO_ACL_Role::FILTER_INACTIVE ?>" />(InActive)</a><br></br>

