<?php

//var_dump($this->dataArray); exit;
//var_dump($this->tableMetaData); exit;
//var_dump($this->tableColumnNames); exit;
$cbArray = '';

// Translates ColumnNames to actual DisplayNames.
//$tableDisplayNames = array( 'title' => 'Media  Universe',
//							'media_class_id' => 'Media Class',
//							'industry_id' => 'Industry',
//							'country_id' => 'Country',
//							'language_id' => 'Language'
//							);
$table_form_name = "AdmAclUser";
?>

<div>
	<table width=100% border=0>
		<caption></caption>
		<tr>
			<td><?php  echo $this->searchbox; ?>
			</td>
			<?php  if (!empty($this->q)) {?>
				<td><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/list/">[X]</a>
				</td>
			<?php } ?>
			<td width=70%>This is the list of users in the system. Administer these records.
			</td>
		</tr>
	</table>
</div>

<?php if (!empty($this->dataArray)){ ?>

<form name="<? echo $table_form_name ?>" action="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/<?php echo $this->myAction; ?>" method="post">
<table class="table_list">
<tr>
	<th>Del</th>
	<?php foreach ($this->tableColumnNames as $column_name) { ?>
		<?php $order_asc = "ORDER_" . $column_name . "_ASC" ?>
		<?php //$$order_asc = $order_asc ?>
		<?php $order_desc = "ORDER_" . $column_name . "_DESC" ?>
		<?php //$$order_desc = $order_desc ?>

		<th>
		<?php if ($this->order == ADMIN_DAO_Media::ORDER_NONE){?>
			<a href="<?php echo $this->url(array('p' => $this->page, 'f' => $this->filter, 'o' => constant("ADMIN_DAO_Media::ORDER_{$column_name}_ASC"))); ?>">
				<?php if (!empty($tableDisplayNames[$column_name])) {?>
					<?php echo ucfirst($tableDisplayNames[$column_name]) ?>
				<?php } else { ?>
					<?php echo ucfirst($column_name) ?>
				<?php } ?>
			</a>
		<?php }else{ ?>
			<?php if ($this->order == constant("ADMIN_DAO_Media::" . $order_asc)) {?>
				<a href="<?php echo $this->url(array('p' => $this->page, 'f' => $this->filter, 'o' => constant("ADMIN_DAO_Media::ORDER_{$column_name}_DESC"))); ?>" style="font:arial,sans-serif; font-weight:bold; color:#00ff00">
					<?php if (!empty($tableDisplayNames[$column_name])) {?>
						<?php echo ucfirst($tableDisplayNames[$column_name]) ?>
					<?php } else { ?>
						<?php echo ucfirst($column_name) ?>
					<?php } ?>
				</a>
			<?php } elseif ($this->order == constant("ADMIN_DAO_Media::" . $order_desc)) { ?>
				<a href="<?php echo $this->url(array('p' => $this->page, 'f' => $this->filter, 'o' => constant("ADMIN_DAO_Media::ORDER_NONE"))); ?>" style="font:arial,sans-serif; font-weight:bold; color:#cc0000">
					<?php if (!empty($tableDisplayNames[$column_name])) {?>
						<?php echo ucfirst($tableDisplayNames[$column_name]) ?>
					<?php } else { ?>
						<?php echo ucfirst($column_name) ?>
					<?php } ?>
				</a>
			<?php } else { ?>
				<a href="<?php echo $this->url(array('p' => $this->page, 'f' => $this->filter, 'o' => constant("ADMIN_DAO_Media::ORDER_{$column_name}_ASC"))); ?>" style="font:arial,sans-serif; color:#000000">
					<?php if (!empty($tableDisplayNames[$column_name])) {?>
						<?php echo ucfirst($tableDisplayNames[$column_name]) ?>
					<?php } else { ?>
						<?php echo ucfirst($column_name) ?>
					<?php } ?>
				</a>
			<?php } ?>
		<?php } ?>
		</th>

	<?php } ?>

</tr>

<?php
foreach($this->dataArray as $record) {
	$cbArray .= $record['id'] .",";
?>
		<tr onMouseover="this.style.backgroundColor='#e0e0e0'" onMouseout="this.style.backgroundColor='#FFFFFF'">
		<td>
			<input type=checkbox name="actioncb_<?php echo $record['id'] ?>">
		</td>
		<td>
			<?php if (!empty($record['id'])){ ?>
			<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/edit/id/<?php echo $record['id'] ?>">
				<?php echo $record['id'] ?>
			</a>
			<?php } ?>
		</td>
		<td>
			<?php if (!empty($record['id'])){ ?>
			<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/edit/id/<?php echo $record['id'] ?>">
				<?php echo $record['login'] ?>
			</a>
			<?php } ?>
		</td>
		<td><?php echo $record['password'] ?></td>
		<td><?php echo $record['title'] ?></td>
		<td><?php echo $record['fullname'] ?></td>
		<td><?php echo $record['firstname'] ?></td>
		<td><?php echo $record['familyname'] ?></td>
		<td><?php echo $record['initials'] ?></td>
		<td><?php echo $record['photo_path'] ?></td>
		<td><?php echo $record['website'] ?></td>
		<td><?php echo $record['package_id'] ?></td>
		<td><?php echo $record['status'] ?></td>
		<td><?php echo $record['language_id'] ?></td>
		<td><?php echo $record['industry_id'] ?></td>
		<td><?php echo $record['invitations'] ?></td>
		<td><?php echo $record['credit'] ?></td>
		<td><?php echo $record['last_login_date'] ?></td>
		<td><?php echo $record['creation_date'] ?></td>
		<td><?php echo $record['last_updated'] ?></td>
	</tr>
<?php } ?>

</table>

<br>
<?php echo $this->Paginator($this->baseURL . '/' . $this->myController . '/' . $this->myAction, $this->page, $this->last_page, $table_form_name); ?>

<?php // echo $this->paginationControl($this->paginator, 'Sliding', 'admin/paginator.phtml'); ?>

<div>
<br><br>
	<table width=100%>
	<tr>
		<td align=left>
			<input class="button" type="submit" value="Update & Stay Here">
			<input type=hidden name="cbArray" value="<?php echo $cbArray; ?>">
			<?php  if (!empty($this->q)) {?>
				<input type=hidden name="q" value="<?php echo $this->q; ?>">
			<?php } ?>


		</td>
	</tr>
	</table>
</div>
</form>


<?php }else{ ?>
	No records found.
<?php } ?>
<br>
<br>

<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/add" />[Add]</a>
<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/emptytable" />[Empty Table]</a>
<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/droptable" />[Drop Table]</a>
<a href="<?php print $this->baseURL; ?>/Admin/" />[Admin Menu]</a>

<br><br>
View Filter<br>
<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/list/f/<?php echo ADMIN_DAO_ACL_User::FILTER_NONE ?>" />(None)</a>
<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/list/f/<?php echo ADMIN_DAO_ACL_User::FILTER_ACTIVE ?>" />(Active)</a>
<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/list/f/<?php echo ADMIN_DAO_ACL_User::FILTER_INACTIVE ?>" />(InActive)</a>

