<?php

//var_dump($this->form_data); exit;

//		$form->addAttribs(array( 'id' => 'acl_user_password')); 		// used for ajaxlogin
//		$form->addAttribs(array( 'onSubmit' => 'return false', )); 	// used for ajaxlogin

?>


<form id="<?php echo $this->element->getAttrib('id'); ?>" onSubmit="<?php echo $this->element->getAttrib('onSubmit'); ?>" method="post" action="/<?php echo $this->element->getAction() ?>" enctype="application/x-www-form-urlencoded">

<table  class="add" align=center width=800 border=0 cellspacing=3>
<caption>
</caption>
<tr>
	<td><label class="required" for="id">User ID</label></td>
	<td><?php echo $this->element->id->getValue(); ?></td>
</tr>
<tr>
	<td><label class="required" for="login">Login</label></td>
	<td><?php echo $this->element->login->getValue(); ?></td>
</tr>
<tr>
	<td><label class="required" for="original_password">Old Password</label></td>
	<td><?php echo $this->element->original_password ?></td>
</tr>
<tr>
	<td><label class="required" for="new_password">New Password</label></td>
	<td><?php echo $this->element->new_password ?>
	</td>
</tr>
<tr>
	<td><label class="required" for="repeat_password">Repeat Password</label></td>
	<td><?php echo $this->element->repeat_password?>
	</td>
</tr>


<tr>
	<td></td>
	<td>
		<?php echo $this->element->submit ?>
	</td>
</tr>



</table>



</form>

<br>
<br>
