<?php

//var_dump($this->dataArray); exit;
//var_dump($this->tableMetaData); exit;
//var_dump($this->tableColumnNames); exit;

?>
<br></br>
	<ul id="tabnav">
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/list" /><<</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/edit/id/<?php echo $this->id ?>" title="tabs-2">User</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/viewpassword/id/<?php echo $this->id ?>" title="tabs-2" class="active">Password</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/viewpackages/id/<?php echo $this->id ?>" title="tabs-5">Packages</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/viewroles/id/<?php echo $this->id ?>" title="tabs-2">Roles</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/viewobjects/id/<?php echo $this->id ?>" title="tabs-3">Objects</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/viewpreferences/id/<?php echo $this->id ?>" title="tabs-4">Preferences</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/viewpaymentmethods/id/<?php echo $this->id ?>">Payment Methods</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/viewtransactions/id/<?php echo $this->id ?>">Transactions</a></li>
	</ul>

		<b>Update your password and click "Change"</b><br>
		
		
		<?php echo $this->form ;?>


