<?php

//var_dump($this->dataArray); exit;
//var_dump($this->tableMetaData); exit;
//var_dump($this->tableColumnNames); exit;

?>
<br></br>
	<ul id="tabnav">
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/list" /><<</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/edit/id/<?php echo $this->id ?>" title="tabs-2">User</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/viewpassword/id/<?php echo $this->id ?>" title="tabs-2">Password</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/viewpackages/id/<?php echo $this->id ?>" title="tabs-5">Packages</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/viewroles/id/<?php echo $this->id ?>" title="tabs-2">Roles</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/viewobjects/id/<?php echo $this->id ?>" title="tabs-3">Objects</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/viewpreferences/id/<?php echo $this->id ?>" title="tabs-4" class="active">Preferences</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/viewpaymentmethods/id/<?php echo $this->id ?>">Payment Methods</a></li>
		<li><a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/viewtransactions/id/<?php echo $this->id ?>">Transactions</a></li>
	</ul>


<?php if (!empty($this->dataArray)){ ?>
<br>
<form name="AdmAclUserPreferences" action="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/<?php echo $this->myAction; ?>" method="post">
<table class="table_list">
<tr>
	<th>Del</th>
	<?php foreach ($this->tableColumnNames as $column_name) { ?>
		<?php $order_asc = "ORDER_" . $column_name . "_ASC" ?>
		<?php //$$order_asc = $order_asc ?>
		<?php $order_desc = "ORDER_" . $column_name . "_DESC" ?>
		<?php //$$order_desc = $order_desc ?>

		<th>
		<?php if ($this->order == ADMIN_DAO_Media::ORDER_NONE){?>
			<a href="<?php echo $this->url(array('p' => $this->page, 'f' => $this->filter, 'o' => constant("ADMIN_DAO_Media::ORDER_{$column_name}_ASC"))); ?>">
				<?php if (!empty($tableDisplayNames[$column_name])) {?>			
					<?php echo ucfirst($tableDisplayNames[$column_name]) ?>
				<?php } else { ?>
					<?php echo ucfirst($column_name) ?>
				<?php } ?>
			</a>
		<?php }else{ ?>
			<?php if ($this->order == constant("ADMIN_DAO_Media::" . $order_asc)) {?>
				<a href="<?php echo $this->url(array('p' => $this->page, 'f' => $this->filter, 'o' => constant("ADMIN_DAO_Media::ORDER_{$column_name}_DESC"))); ?>" style="font:arial,sans-serif; font-weight:bold; color:#00ff00">
					<?php if (!empty($tableDisplayNames[$column_name])) {?>			
						<?php echo ucfirst($tableDisplayNames[$column_name]) ?>
					<?php } else { ?>
						<?php echo ucfirst($column_name) ?>
					<?php } ?>
				</a>
			<?php } elseif ($this->order == constant("ADMIN_DAO_Media::" . $order_desc)) { ?>
				<a href="<?php echo $this->url(array('p' => $this->page, 'f' => $this->filter, 'o' => constant("ADMIN_DAO_Media::ORDER_NONE"))); ?>" style="font:arial,sans-serif; font-weight:bold; color:#cc0000">
					<?php if (!empty($tableDisplayNames[$column_name])) {?>			
						<?php echo ucfirst($tableDisplayNames[$column_name]) ?>
					<?php } else { ?>
						<?php echo ucfirst($column_name) ?>
					<?php } ?>
				</a>
			<?php } else { ?>
				<a href="<?php echo $this->url(array('p' => $this->page, 'f' => $this->filter, 'o' => constant("ADMIN_DAO_Media::ORDER_{$column_name}_ASC"))); ?>" style="font:arial,sans-serif; color:#000000">
					<?php if (!empty($tableDisplayNames[$column_name])) {?>			
						<?php echo ucfirst($tableDisplayNames[$column_name]) ?>
					<?php } else { ?>
						<?php echo ucfirst($column_name) ?>
					<?php } ?>
				</a>
			<?php } ?>
		<?php } ?>
		</th>
		
	<?php } ?>

</tr>
<?php
foreach($this->paginator as $record) {
?>
	<tr>
		<td>
			<input type=checkbox name="actioncb_<?php echo $record['id'] ?>">
		</td>
		<td>
			<?php if (!empty($record['id'])){ ?>
			<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/edit/id/<?php echo $record['id'] ?>">
				<?php echo $record['id'] ?>
			</a>
			<?php } ?>
		</td>
		<td>
			<?php if (!empty($record['id'])){ ?>
			<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/edit/id/<?php echo $record['id'] ?>">
				<?php echo $this->getUserLogin($record['user_id']) ?>
			</a>
			<?php } ?>
		</td>
		<td><?php echo $this->getPreference($record['preference_id']) ?></td>
		<td><?php echo $record['status'] ?></td>
		<td><?php echo $record['creation_date'] ?></td>
		<td><?php echo $record['last_updated'] ?></td>
	</tr>

<?php } ?>

</table>
<br>
<?php echo $this->Paginator($this->baseURL . '/' . $this->myController . '/' . $this->myAction, $this->page, $this->last_page, 'AdmAclUserPreferences'); ?>

<?php // echo $this->paginationControl($this->paginator, 'Sliding', 'admin/paginator.phtml'); ?>

<div>
<br><br>
	<table width=100%>
	<tr>
		<td align=left>
			<input class="button" type="submit" value="Update & Stay Here">
			<input id="add_role_button" type="button" value="Add Role">
			<input type=hidden name="cbArray" value="<?php echo $cbArray; ?>">
			<?php  if (!empty($this->q)) {?>
				<input type=hidden name="q" value="<?php echo $this->q; ?>">
			<?php } ?>
			
			
		</td>
	</tr>
	</table>

<?php }else{ ?>
	No records found.
<?php } ?>

<br>
<br><br>
View Filter<br>
<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/<?php echo $this->myAction; ?>/f/<?php echo ADMIN_DAO_ACL_User::FILTER_NONE ?>" />(None)</a>
<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/<?php echo $this->myAction; ?>/f/<?php echo ADMIN_DAO_ACL_User::FILTER_ACTIVE ?>" />(Active)</a>
<a href="<?php print $this->baseURL; ?>/<?php echo $this->myController; ?>/<?php echo $this->myAction; ?>/f/<?php echo ADMIN_DAO_ACL_User::FILTER_INACTIVE ?>" />(InActive)</a>

