<?php

//var_dump($this->form_data); exit;

?>

<form id="media" method="post" action="/<?php echo $this->element->getAction() ?>" enctype="application/x-www-form-urlencoded">

<table  class="add" align=center width=800 border=0 cellspacing=3>
<caption>
</caption>
<tr>
	<td><label class="required" for="login">User ID</label></td>
	<td><?php echo $this->element->id->getValue(); ?></td>
</tr>
<tr>
	<td><label class="required" for="login">Login</label></td>
	<td><?php echo $this->element->login->getValue(); ?></td>
</tr>
<tr>
	<td><label class="required" for="title">Title</label></td>
	<td><?php echo $this->element->title ?></td>
</tr>
<tr>
	<td><label class="required" for="fullname">Full Name</label></td>
	<td><?php echo $this->element->fullname->getValue() ?>
	</td>
</tr>
<tr>
	<td><label class="required" for="firstname">First Name</label></td>
	<td><?php echo $this->element->firstname ?>
	</td>
</tr>
<tr>
	<td><label class="required" for="familyname">Family Name</label></td>
	<td><?php echo $this->element->familyname ?>
	</td>
</tr>

<tr>
	<td><label class="required" for="initials">Initials</label></td>
	<td><?php echo $this->element->initials ?>
	</td>
</tr>

<tr>
	<td><label class="required" for="photo_path">Photo Path</label></td>
	<td><?php echo $this->element->photo_path ?>
	</td>
</tr>

<tr>
	<td><label class="required" for="website">Website</label></td>
	<td><?php echo $this->element->website ?>
	</td>
</tr>


<tr>
	<td><label class="required" for="media_url">Package</label></td>
	<td><?php echo $this->element->package_id ?>
	</td>
</tr>

<tr>
	<td><label class="required" for="status">Status</label></td>
	<td>
		<?php echo $this->element->status ?>
	</td>
</tr>
<tr>
	<td><label class="required" for="industry_id">Industry</label></td>
	<td>
		<?php echo $this->element->industry_id_input ?>
		<?php echo $this->element->industry_id ?>
	</td>
</tr>
<tr>
	<td><label class="required" for="language_id">Language</label></td>
	<td>
		<?php echo $this->element->language_id_input ?>
		<?php echo $this->element->language_id ?>
	</td>
</tr>

<tr>
	<td><label class="required" for="invitations">Invitations</label></td>
	<td><?php echo $this->element->invitations ?>
	</td>
</tr>

<tr>
	<td><label class="required" for="credit">Credit</label></td>
	<td><?php echo $this->element->credit ?>
	</td>
</tr>

<tr>
	<td><label class="required" for="last_login_date">Last Login</label></td>
	<td><?php echo $this->element->last_login_date->getValue(); ?>
	</td>
</tr>

<tr>
	<td><label class="required" for="last_updated">Last Updated</label></td>
	<td><?php echo $this->element->last_updated->getValue(); ?>
	</td>
</tr>

<tr>
	<td><label class="required" for="creation_date">Creation Date</label></td>
	<td><?php echo $this->element->creation_date->getValue(); ?>
	</td>
</tr>


<tr>
	<td></td>
	<td>
		<?php echo $this->element->submit ?>
	</td>
</tr>



</table>



</form>

<br>
<br>
